import csv
import json
import os
import re
import time
from collections import Counter
from pathlib import Path
from typing import Dict, List, Any, Tuple

import chromadb
from dotenv import load_dotenv
from openai import OpenAI


# =========================================================
# Paths / config
# =========================================================
BASE_DIR = Path(__file__).resolve().parent.parent

VECTOR_PATH = BASE_DIR / "vector_db"
COLLECTION_NAME = "policy_db_main_openai"

INPUT_CATALOG = (
    BASE_DIR
    / "outputs"
    / "rag_index_v1_openai"
    / "policy_catalog_main_for_rag_0512.csv"
)

OUTPUT_DIR = BASE_DIR / "outputs" / "instrument_extract_v3"

# Full audit table: complete output for validation, traceability, and SI.
OUTPUT_RECORDS = OUTPUT_DIR / "instrument_audit_table_0512.csv"

# Raw policy summary generated by the extraction process.
OUTPUT_SUMMARY = OUTPUT_DIR / "policy_instrument_summary_raw_0512.csv"

# Clean analysis-ready tables.
OUTPUT_POLICY_ANALYSIS = OUTPUT_DIR / "policy_level_analysis_0512.csv"
OUTPUT_MIX_ANALYSIS = OUTPUT_DIR / "instrument_mix_analysis_0512.csv"

# Run log.
OUTPUT_LOG = OUTPUT_DIR / "instrument_extract_log_0512.csv"

DEFAULT_MODEL = "gpt-4.1-mini"
DEFAULT_EMBEDDING_MODEL = "text-embedding-3-small"

MAX_CHARS_PER_BATCH = 18000
SLEEP_SECONDS = 1
RETRY_TIMES = 4

# =========================
# Testing / formal settings
# =========================
TEST_LIMIT = None
RESUME_FROM_EXISTING = True

# Formal run:
# TEST_LIMIT = None
# RESUME_FROM_EXISTING = True

MIN_CONFIDENCE_KEEP = 0.70
EXCLUDE_GENERAL_MEDICAL_BIOTECH = True

# Calibration is stricter in this version.
# Use 2 for moderate strictness; use 3 for conservative calibration reporting.
CALIBRATION_THRESHOLD = 2

# For quick testing, set 3 or 5.
# For formal run, keep None.
MAX_BATCHES_PER_POLICY = None


# =========================================================
# Retrieval + context-window settings
# =========================================================
USE_RETRIEVAL_CONTEXT_WINDOWS = True

# Each query retrieves top-k seed chunks under policy_id metadata filter.
N_RESULTS_PER_QUERY = 8
MAX_SEED_CHUNKS_PER_POLICY = 20

# Reconstruct local context around each seed chunk.
# With TARGET_CHUNK_CHARS ≈ 6000, before=1 and after=1 gives ~18000 chars.
CONTEXT_EXPAND_BEFORE = 1
CONTEXT_EXPAND_AFTER = 1

# Max size of each reconstructed context window.
MAX_CONTEXT_CHARS = 18000

# Max context windows per policy after merging/ranking.
MAX_CONTEXT_WINDOWS_PER_POLICY = 12

RETRIEVAL_QUERIES = [
    "bioeconomy policy instruments funding subsidies grants loans tax incentives public procurement",
    "bioeconomy regulation standards certification labelling licensing quotas mandatory requirements",
    "bioeconomy implementation agency working group coordination monitoring evaluation reporting",
    "bioeconomy cooperation networks partnerships councils consultation science industry collaboration",
    "bioenergy biofuels biogas biomethane biomass residues biorefinery policy instruments",
    "bio-based materials bio-based chemicals bioplastics biodegradable materials industrial biotechnology policy measures",
]


# =========================================================
# Env / clients
# =========================================================
load_dotenv(BASE_DIR / ".env", override=True)

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
MODEL_NAME = os.getenv("OPENAI_MODEL", DEFAULT_MODEL)
EMBEDDING_MODEL = os.getenv("OPENAI_EMBEDDING_MODEL", DEFAULT_EMBEDDING_MODEL)

if not OPENAI_API_KEY:
    raise RuntimeError("OPENAI_API_KEY not found in .env")

oa_client = OpenAI(api_key=OPENAI_API_KEY)
chroma_client = chromadb.PersistentClient(path=str(VECTOR_PATH))
collection = chroma_client.get_collection(COLLECTION_NAME)


# =========================================================
# Basic helpers
# =========================================================
def clean_str(value) -> str:
    if value is None:
        return ""
    return str(value).strip()


def normalize_text(text: str) -> str:
    text = str(text or "")
    text = text.replace("\u00a0", " ")
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


def safe_float(value, default: float = 0.0) -> float:
    try:
        return float(value)
    except Exception:
        return default


def safe_int(value, default: int = 0) -> int:
    try:
        return int(float(value))
    except Exception:
        return default


def safe_int01(value) -> int:
    if isinstance(value, bool):
        return 1 if value else 0
    if isinstance(value, int):
        return 1 if value == 1 else 0
    if isinstance(value, float):
        return 1 if int(value) == 1 else 0

    s = clean_str(value).lower()
    if s in {"1", "true", "yes", "present"}:
        return 1
    return 0


def normalize_bool(value) -> bool:
    if isinstance(value, bool):
        return value
    return clean_str(value).lower() in {"true", "yes", "1"}


def load_csv(path: Path) -> List[Dict[str, Any]]:
    if not path.exists():
        raise FileNotFoundError(f"File not found: {path}")
    with open(path, "r", encoding="utf-8-sig", newline="") as f:
        return list(csv.DictReader(f))


def load_optional_csv(path: Path) -> List[Dict[str, Any]]:
    if not path.exists():
        return []
    with open(path, "r", encoding="utf-8-sig", newline="") as f:
        return list(csv.DictReader(f))


def save_csv(path: Path, rows: List[Dict[str, Any]], fieldnames: List[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8-sig", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)


def remove_policy_rows(rows: List[Dict[str, Any]], policy_id: str) -> List[Dict[str, Any]]:
    return [row for row in rows if clean_str(row.get("policy_id")) != policy_id]


def parse_json_object(text: str) -> Dict[str, Any]:
    text = text.strip()
    match = re.search(r"\{.*\}", text, re.S)
    if not match:
        raise ValueError("No JSON object found in model output")
    return json.loads(match.group(0))


def simpson_balance(type_counts: Dict[str, int]) -> float:
    counts = [v for v in type_counts.values() if v > 0]
    total = sum(counts)

    if total <= 1:
        return 0.0

    numerator = sum(n * (n - 1) for n in counts)
    denominator = total * (total - 1)
    return round(1 - numerator / denominator, 4)


def load_existing_state():
    record_rows = load_optional_csv(OUTPUT_RECORDS)
    summary_rows = load_optional_csv(OUTPUT_SUMMARY)
    log_rows = load_optional_csv(OUTPUT_LOG)

    log_by_policy = {}
    for row in log_rows:
        policy_id = clean_str(row.get("policy_id"))
        if policy_id:
            log_by_policy[policy_id] = row

    return record_rows, summary_rows, log_rows, log_by_policy


# =========================================================
# Classification system
# =========================================================
CLASSIFICATION_SYSTEM = {
    "Economic": {
        "Infrastructure": [
            "Establishment of specific research facilities",
            "Establishment of pilot and demonstration plants",
            "Creation of Industry parks",
            "Promotion/creation of Biorefineries",
            "Development of technology platforms",
        ],
        "Direct support": [
            "Input support schemes",
            "Technical Support by Government (Agency)",
            "Funding of research/innovation projects",
            "Funding of industry/business",
            "Adaptation Funding for Industry/Business",
            "Innovation Funding for Industry/Business",
            "Funding of Vocational Training Schemes",
            "Public procurement programmes",
            "Tax/Fee reductions for producers",
            "Tax/Fee reductions for consumers",
            "Subsidies for producers",
            "Subsidies for consumers",
            "Credit/Loan Schemes",
            "Grants",
            "Payment for Ecosystem Services",
            "Emission Trade Market",
        ],
        "Indirect support": [
            "Local content requirements",
            "Import/Export restrictions",
            "Import/Export incentives",
        ],
    },
    "Informational": {
        "Informational": [
            "Research Council",
            "Creation of public dialogue platforms",
            "National Bioeconomy Websites (Platforms)",
            "Media Campaigns/Advertisement",
            "Reports",
            "Public (not vocational) Training/Education Programmes",
            "Market Intelligence Collection/Dissemination",
        ]
    },
    "Regulatory": {
        "Regulatory": [
            "Licenses",
            "Private and public standards, certifications and labelling",
            "Regulation (generic)",
            "Intellectual Property Right Regulation",
            "Production Objectives/Quotas",
            "Pigouvian Taxes",
        ]
    },
    "Administrative": {
        "Administrative": [
            "(Instrument) Bottom-Up Decision Making",
            "(Instrument) Decentralized decision making",
            "Abolishment/change of impeding instruments",
            "Monitoring/Measuring",
            "Measuring Entity Creation",
            "Inter-Authority/Ministry Coordination",
            "Intergovernmental Coordination",
            "Revision of other bioeconomy related policies",
            "Regular reviews of policies (learning loops)",
            "Regulatory Authority Creation",
            "FDI Promotion Agency Creation",
            "Public Enterprise Creation",
            "Creation of international organizations/regimes/partnerships",
            "Bioeconomy Entity/Body",
        ]
    },
    "Cooperative": {
        "Cooperative": [
            "Cooperation of policy, business, academia & civil society",
            "National bioeconomy council (generic)",
            "Facilitation of policy, research and industry network/cooperation",
            "Facilitation of research networks/cooperation/partners",
            "Facilitation of science and industry networks/cooperation",
            "Facilitation of science and policy networks/cooperation",
            "Facilitation of industry and policy networks/cooperation",
            "Facilitation of industry networks/cooperation/partners",
            "Facilitation of Scientific Advisory Councils",
            "Facilitation of Business Advisory Councils",
            "Facilitation of Public Advisory Councils",
            "Grassroot-stakeholder consultation (Instrument)",
            "Broad/Cross-stakeholder consultation (Instrument)",
        ]
    },
}

ALLOWED_SUBTYPES = []
SUBTYPE_TO_TYPE = {}
SUBTYPE_TO_GROUP = {}

for instrument_type, groups in CLASSIFICATION_SYSTEM.items():
    for instrument_group, subtypes in groups.items():
        for subtype in subtypes:
            ALLOWED_SUBTYPES.append(subtype)
            SUBTYPE_TO_TYPE[subtype] = instrument_type
            SUBTYPE_TO_GROUP[subtype] = instrument_group


# =========================================================
# Harmonized subtype mapping
# =========================================================
COOPERATIVE_HARMONIZATION = {
    "Cooperation of policy, business, academia & civil society": "Multi-stakeholder cooperation",
    "Facilitation of policy, research and industry network/cooperation": "Multi-stakeholder cooperation",
    "Facilitation of research networks/cooperation/partners": "Science/research cooperation",
    "Facilitation of science and industry networks/cooperation": "Science-industry cooperation",
    "Facilitation of science and policy networks/cooperation": "Science-policy cooperation",
    "Facilitation of industry and policy networks/cooperation": "Industry-policy cooperation",
    "Facilitation of industry networks/cooperation/partners": "Industry cooperation",
    "Grassroot-stakeholder consultation (Instrument)": "Consultation mechanism",
    "Broad/Cross-stakeholder consultation (Instrument)": "Consultation mechanism",
    "National bioeconomy council (generic)": "Advisory council",
    "Facilitation of Scientific Advisory Councils": "Advisory council",
    "Facilitation of Business Advisory Councils": "Advisory council",
    "Facilitation of Public Advisory Councils": "Advisory council",
}


def harmonize_subtype(subtype: str) -> str:
    subtype = clean_str(subtype)
    return COOPERATIVE_HARMONIZATION.get(subtype, subtype)


# =========================================================
# Calibration fields
# =========================================================
CALIBRATION_FIELDS = [
    "calibration_implementer",
    "calibration_funding",
    "calibration_implementing_partner",
    "calibration_timeframe",
    "calibration_target_group",
    "calibration_procedure",
    "calibration_content",
    "calibration_objective",
]


# =========================================================
# Output fields
# =========================================================
RECORD_FIELDNAMES = [
    "policy_id",
    "faolex_no",
    "jurisdiction",
    "policy_year",
    "title",
    "non_food_bio_based_sector",
    "record_id",
    "instrument_type",
    "instrument_group",
    "instrument_subtype",
    "instrument_subtype_harmonized",
    "raw_subtypes_collapsed",
    "linked_domain",
    "evidence_mention_count",
    "evidence_batch_ids",
    "representative_measure_text",
    "representative_justification",
    "evidence_examples",
    *CALIBRATION_FIELDS,
    "calibration_score",
    "calibrated_yes_no",
    "confidence",
    "avg_confidence_internal",
]

SUMMARY_FIELDNAMES = [
    "policy_id",
    "faolex_no",
    "jurisdiction",
    "policy_year",
    "title",
    "non_food_bio_based_sector",
    "original_chunk_count",
    "seed_chunk_count",
    "context_chunk_count",
    "batch_count",
    "instrument_record_count",
    "raw_evidence_mention_count",
    "distinct_instrument_types",
    "distinct_instrument_subtypes_raw",
    "distinct_instrument_subtypes_harmonized",
    "Economic",
    "Informational",
    "Regulatory",
    "Administrative",
    "Cooperative",
    "Simpson_balance",
    "calibrated_record_count",
    "calibrated_record_share",
    "avg_calibration_score",
    "avg_confidence",
]

LOG_FIELDNAMES = [
    "policy_id",
    "status",
    "message",
    "original_chunk_count",
    "seed_chunk_count",
    "context_chunk_count",
    "batch_count",
    "instrument_record_count",
    "raw_evidence_mention_count",
]


# =========================================================
# Clean analysis output fields
# =========================================================
POLICY_LEVEL_ANALYSIS_FIELDNAMES = [
    "policy_id",
    "faolex_no",
    "jurisdiction",
    "policy_year",
    "title",
    "non_food_bio_based_sector",
    "instrument_record_count",
    "distinct_instrument_types",
    "distinct_instrument_subtypes_harmonized",
    "Economic",
    "Regulatory",
    "Administrative",
    "Cooperative",
    "Informational",
    "dominant_instrument_type",
    "dominant_instrument_share",
    "policy_mix_profile",
    "Simpson_balance",
    "calibrated_record_share",
    "avg_calibration_score",
    "original_chunk_count",
    "seed_chunk_count",
    "context_chunk_count",
    "retrieval_coverage",
    "batch_count",
]

INSTRUMENT_MIX_ANALYSIS_FIELDNAMES = [
    "policy_id",
    "faolex_no",
    "jurisdiction",
    "policy_year",
    "title",
    "non_food_bio_based_sector",
    "record_id",
    "instrument_type",
    "instrument_subtype_harmonized",
    "linked_domain",
    "calibration_score",
    "calibrated_yes_no",
    "representative_measure_text",
]


# =========================================================
# Domain normalization
# =========================================================
ALLOWED_DOMAINS = {
    "bioenergy",
    "biofuels",
    "biogas",
    "biobased_materials",
    "biochemicals",
    "industrial_biotechnology",
    "biorefinery",
    "biomass_residue_valorization",
    "wood_fiber_materials",
    "forestry_biotechnology",
    "cross_sectoral_bioeconomy",
}

DOMAIN_ALIASES = {
    "bio-based_materials": "biobased_materials",
    "bio_based_materials": "biobased_materials",
    "bio-based materials": "biobased_materials",
    "bio based materials": "biobased_materials",
    "biomass_residue_utilisation": "biomass_residue_valorization",
    "biomass_residue_utilization": "biomass_residue_valorization",
    "biomass residue valorization": "biomass_residue_valorization",
    "biomass residue utilization": "biomass_residue_valorization",
    "waste_valorization": "biomass_residue_valorization",
    "wood_fiber": "wood_fiber_materials",
    "wood_fibre_materials": "wood_fiber_materials",
    "wood/fiber_materials": "wood_fiber_materials",
    "wood and fiber materials": "wood_fiber_materials",
    "cross-sectoral_bioeconomy": "cross_sectoral_bioeconomy",
    "cross sectoral bioeconomy": "cross_sectoral_bioeconomy",
}


def normalize_domain(value: str) -> str:
    domain = clean_str(value).lower()
    return DOMAIN_ALIASES.get(domain, domain)


# =========================================================
# Vector DB chunks and context-window retrieval
# =========================================================
def get_chunk_order_value(ch: Dict[str, Any]) -> int:
    cid = clean_str(ch.get("chunk_id"))
    try:
        return int(float(cid))
    except Exception:
        return 999999


def sort_chunks_by_chunk_id(chunks: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    return sorted(chunks, key=get_chunk_order_value)


def get_policy_chunks(policy_id: str) -> List[Dict[str, Any]]:
    data = collection.get(
        where={"policy_id": policy_id},
        include=["documents", "metadatas"],
    )

    docs = data.get("documents", [])
    metas = data.get("metadatas", [])

    chunks = []
    for doc, meta in zip(docs, metas):
        chunks.append({
            "text": normalize_text(doc),
            "section_title": clean_str(meta.get("section_title")),
            "chunk_id": meta.get("chunk_id"),
        })

    return sort_chunks_by_chunk_id(chunks)


def embed_retrieval_queries(queries: List[str]) -> List[List[float]]:
    if not queries:
        return []

    resp = oa_client.embeddings.create(
        model=EMBEDDING_MODEL,
        input=queries,
    )

    return [item.embedding for item in resp.data]


def retrieve_seed_chunks(
    policy_id: str,
    retrieval_query_embeddings: List[List[float]],
) -> List[Dict[str, Any]]:
    if not retrieval_query_embeddings:
        return []

    seeds = {}

    for query_emb in retrieval_query_embeddings:
        try:
            res = collection.query(
                query_embeddings=[query_emb],
                where={"policy_id": policy_id},
                n_results=N_RESULTS_PER_QUERY,
                include=["documents", "metadatas", "distances"],
            )

            docs = res.get("documents", [[]])[0]
            metas = res.get("metadatas", [[]])[0]
            distances = res.get("distances", [[]])[0]

            for rank, (doc, meta, dist) in enumerate(zip(docs, metas, distances)):
                cid = clean_str(meta.get("chunk_id"))
                if not cid:
                    continue

                rank_score = 1.0 / (rank + 1)

                if cid not in seeds:
                    seeds[cid] = {
                        "chunk_id": cid,
                        "text": normalize_text(doc),
                        "section_title": clean_str(meta.get("section_title")),
                        "retrieval_score": 0.0,
                        "retrieval_hits": 0,
                        "best_distance": dist,
                    }

                seeds[cid]["retrieval_score"] += rank_score
                seeds[cid]["retrieval_hits"] += 1

                try:
                    seeds[cid]["best_distance"] = min(seeds[cid]["best_distance"], dist)
                except Exception:
                    pass

        except Exception as e:
            print(f"[Seed retrieval warning] {policy_id}: {e}")
            return []

    seed_chunks = list(seeds.values())
    seed_chunks.sort(
        key=lambda ch: (
            float(ch.get("retrieval_score", 0.0)),
            int(ch.get("retrieval_hits", 0)),
        ),
        reverse=True,
    )

    return seed_chunks[:MAX_SEED_CHUNKS_PER_POLICY]


def build_context_windows_from_seeds(
    all_chunks: List[Dict[str, Any]],
    seed_chunks: List[Dict[str, Any]],
) -> List[List[Dict[str, Any]]]:
    if not all_chunks:
        return []

    all_chunks = sort_chunks_by_chunk_id(all_chunks)

    chunk_by_id = {}
    ordered_ids = []

    for ch in all_chunks:
        cid = clean_str(ch.get("chunk_id"))
        if not cid:
            continue

        chunk_by_id[cid] = {
            "chunk_id": cid,
            "text": clean_str(ch.get("text")),
            "section_title": clean_str(ch.get("section_title")),
        }
        ordered_ids.append(cid)

    id_to_pos = {cid: i for i, cid in enumerate(ordered_ids)}
    raw_windows = []

    for seed in seed_chunks:
        seed_id = clean_str(seed.get("chunk_id"))
        if seed_id not in id_to_pos:
            continue

        seed_pos = id_to_pos[seed_id]
        seed_section = clean_str(chunk_by_id[seed_id].get("section_title"))

        start_pos = max(0, seed_pos - CONTEXT_EXPAND_BEFORE)
        end_pos = min(len(ordered_ids) - 1, seed_pos + CONTEXT_EXPAND_AFTER)

        window_ids = []

        for pos in range(start_pos, end_pos + 1):
            cid = ordered_ids[pos]
            ch = chunk_by_id[cid]
            ch_section = clean_str(ch.get("section_title"))

            if seed_section and ch_section and ch_section != seed_section:
                continue

            window_ids.append(cid)

        if not window_ids:
            window_ids = [seed_id]

        raw_windows.append({
            "seed_id": seed_id,
            "seed_score": float(seed.get("retrieval_score", 0.0)),
            "section_title": seed_section,
            "chunk_ids": set(window_ids),
        })

    merged = []

    for win in raw_windows:
        placed = False

        for existing in merged:
            same_section = (
                clean_str(existing.get("section_title"))
                and clean_str(existing.get("section_title")) == clean_str(win.get("section_title"))
            )

            overlap = bool(existing["chunk_ids"].intersection(win["chunk_ids"]))

            existing_positions = [id_to_pos[cid] for cid in existing["chunk_ids"] if cid in id_to_pos]
            new_positions = [id_to_pos[cid] for cid in win["chunk_ids"] if cid in id_to_pos]

            adjacent = False
            if existing_positions and new_positions:
                adjacent = min(abs(a - b) for a in existing_positions for b in new_positions) <= 1

            if overlap or (same_section and adjacent):
                existing["chunk_ids"].update(win["chunk_ids"])
                existing["seed_score"] = max(existing["seed_score"], win["seed_score"])
                placed = True
                break

        if not placed:
            merged.append(win)

    context_windows = []

    for win in merged:
        ids_sorted = sorted(
            win["chunk_ids"],
            key=lambda cid: id_to_pos.get(cid, 999999),
        )

        current = []
        current_chars = 0

        for cid in ids_sorted:
            ch = chunk_by_id[cid]
            ch_len = len(clean_str(ch.get("text")))

            if current and current_chars + ch_len > MAX_CONTEXT_CHARS:
                context_windows.append(current)
                current = []
                current_chars = 0

            current.append(ch)
            current_chars += ch_len

        if current:
            context_windows.append(current)

    def window_score(window):
        ids = {clean_str(ch.get("chunk_id")) for ch in window}
        score = 0.0

        for seed in seed_chunks:
            if clean_str(seed.get("chunk_id")) in ids:
                score += float(seed.get("retrieval_score", 0.0))

        return score

    context_windows.sort(
        key=lambda w: (
            window_score(w),
            -get_chunk_order_value(w[0]) if w else -999999,
        ),
        reverse=True,
    )

    context_windows = context_windows[:MAX_CONTEXT_WINDOWS_PER_POLICY]
    context_windows.sort(key=lambda w: get_chunk_order_value(w[0]) if w else 999999)

    return context_windows


def build_context_window_batches(context_windows: List[List[Dict[str, Any]]]) -> List[str]:
    batches = []

    for batch_i, window in enumerate(context_windows, start=1):
        parts = []

        for j, ch in enumerate(window, start=1):
            chunk_id = clean_str(ch.get("chunk_id"))
            section = clean_str(ch.get("section_title")) or "UNKNOWN_SECTION"
            text = clean_str(ch.get("text"))

            block = (
                f"[ContextBatch {batch_i} | Chunk {j} | chunk_id={chunk_id} | "
                f"Section: {section}]\n{text}\n"
            )
            parts.append(block)

        batches.append("\n\n".join(parts).strip())

    return batches


def build_chunk_batches(
    chunks: List[Dict[str, Any]],
    max_chars: int = MAX_CHARS_PER_BATCH,
) -> List[str]:
    batches = []
    current_parts = []
    current_len = 0

    for i, ch in enumerate(chunks, start=1):
        section = clean_str(ch.get("section_title")) or "UNKNOWN_SECTION"
        chunk_id = clean_str(ch.get("chunk_id")) or str(i)
        text = clean_str(ch.get("text"))

        if not text:
            continue

        block = f"[FullBatch | Chunk {i} | chunk_id={chunk_id} | Section: {section}]\n{text}\n"

        if current_parts and current_len + len(block) > max_chars:
            batches.append("\n\n".join(current_parts).strip())
            current_parts = []
            current_len = 0

        current_parts.append(block)
        current_len += len(block)

    if current_parts:
        batches.append("\n\n".join(current_parts).strip())

    if MAX_BATCHES_PER_POLICY is not None:
        batches = batches[:MAX_BATCHES_PER_POLICY]

    return batches


def retrieve_context_batches_for_policy(
    policy_id: str,
    all_chunks: List[Dict[str, Any]],
    retrieval_query_embeddings: List[List[float]],
) -> Tuple[List[str], int, int]:
    seed_chunks = retrieve_seed_chunks(
        policy_id=policy_id,
        retrieval_query_embeddings=retrieval_query_embeddings,
    )

    if not seed_chunks:
        print("  - No seed chunks found; fallback to full-text batches")
        batches = build_chunk_batches(all_chunks)
        return batches, 0, len(all_chunks)

    context_windows = build_context_windows_from_seeds(
        all_chunks=all_chunks,
        seed_chunks=seed_chunks,
    )

    if not context_windows:
        print("  - No context windows built; fallback to full-text batches")
        batches = build_chunk_batches(all_chunks)
        return batches, len(seed_chunks), len(all_chunks)

    batches = build_context_window_batches(context_windows)

    unique_context_chunk_ids = set()
    for window in context_windows:
        for ch in window:
            cid = clean_str(ch.get("chunk_id"))
            if cid:
                unique_context_chunk_ids.add(cid)

    if MAX_BATCHES_PER_POLICY is not None:
        batches = batches[:MAX_BATCHES_PER_POLICY]

    return batches, len(seed_chunks), len(unique_context_chunk_ids)


# =========================================================
# Prompt
# =========================================================
def build_prompt(
    context: str,
    policy_id: str,
    title: str,
    jurisdiction: str,
    policy_year: str,
    sector: str,
    batch_id: int,
    batch_count: int,
) -> str:
    classification_json = json.dumps(CLASSIFICATION_SYSTEM, ensure_ascii=False, indent=2)

    medical_rule = (
        "General medical biotechnology, pharmaceuticals, vaccines, clinical medicine, hospitals, "
        "public health, medical devices, and drug approval must be excluded unless the measure is "
        "explicitly about industrial biotechnology, biomass conversion, bio-based industrial production, "
        "or another non-food biomass use."
        if EXCLUDE_GENERAL_MEDICAL_BIOTECH
        else
        "Medical biotechnology is not automatically excluded, but it must still satisfy the direct non-food bioeconomy relevance gate."
    )

    return f"""
You are coding compact policy instrument records for a global non-food bioeconomy policy dataset.

Important:
Your task is NOT to extract every minor action, sentence, clause, article, example, or implementation detail.
Your task is to identify the policy instrument subtypes present in the focal policy document, supported by representative evidence.

A compact policy instrument record refers to one instrument subtype within one linked non-food bioeconomy domain in the focal policy document.

Focal policy metadata:
- policy_id: {policy_id}
- jurisdiction: {jurisdiction}
- policy_year: {policy_year}
- title: {title}
- existing sector label: {sector}
- current batch: {batch_id} of {batch_count}

Apply the following gates in order.

GATE 1 — Jurisdiction attribution:
Keep only instruments proposed, mandated, financed, regulated, coordinated, adopted, or operationalized by the focal jurisdiction of this policy document.
Exclude instruments that are only mentioned as external context, examples, background, previous initiatives, or policy environment.
This includes EU, OECD, UN, World Bank, foreign-government, international organization, or other external policy actions unless the focal jurisdiction explicitly states it will adopt, implement, fund, transpose, operationalize, or coordinate them.

GATE 2 — Instrument gate:
Keep only concrete instruments.
Exclude goals, visions, rationales, problem descriptions, background statements, evaluations, reviews, findings, claims that further investment is needed, or broad statements that something should be promoted.
A statement is not an instrument merely because it contains words such as support, promote, strengthen, enhance, encourage, improve, accelerate, facilitate, develop, or advance.
It must specify a real tool, mechanism, programme, fund, standard, regulation, platform, body, monitoring system, procurement scheme, cooperation mechanism, or administrative arrangement.

GATE 3 — Non-food bioeconomy relevance:
Keep only instruments directly linked to non-food bioeconomy domains, including:
bioenergy, biofuels, biodiesel, bioethanol, biogas, biomethane, bio-based materials, bio-based chemicals, bioplastics, biodegradable materials, industrial biotechnology, bio-manufacturing, bio-processing, biorefineries, biomass residue valorization, agricultural residues, forestry residues, organic waste valorization, wood/fiber/bamboo-based material uses, forestry biotechnology for non-food purposes, and other clearly stated non-food uses of biomass or bio-based resources.

Exclude general climate, environmental, biodiversity, circular economy, green growth, renewable energy, energy efficiency, distributed generation, forestry, agriculture, innovation, manufacturing, or industrial policy measures unless the measure itself or its immediate surrounding context explicitly identifies biomass, bioenergy, biofuel, biogas, biomethane, bio-based materials, industrial biotechnology, biorefinery, biomass residues, wood/fiber materials, or another non-food biomass use.

Do not rely on the document title or sector label alone to convert a broad renewable-energy, forestry, agriculture, or industrial measure into a non-food bioeconomy instrument. The title or sector label may support the decision only when the specific measure is also located in a clearly biomass/bioenergy/bio-based section or immediate context.

Exclude general recycling, general circular economy, general waste management, general sustainable materials, general plastics recycling, and general construction-material reuse unless the measure explicitly identifies bio-based materials, biomass, biogenic resources, organic waste, agricultural residues, forestry residues, wood, fiber, bamboo, bioplastics, biodegradable materials, or another non-food biomass use.

Exclude fossil energy measures, including shale gas, natural gas, petroleum, coal, LPG, and fossil fuels.
{medical_rule}

Domain assignment rule:
Use cross_sectoral_bioeconomy only when the instrument explicitly applies to the bioeconomy as a whole or to multiple clearly stated non-food bioeconomy domains.
Do NOT use cross_sectoral_bioeconomy as a fallback when the specific domain is unclear.
If the non-food bioeconomy domain is unclear and no direct domain can be identified, exclude the record.

GATE 4 — Compact instrument coding:
Code instruments at the level of policy instrument subtype within each linked domain, not at the level of every minor action, clause, article, example, implementation detail, or repeated mention.

Within this batch, do not create multiple records for repeated examples, sub-actions, implementation details, or variants of the same instrument subtype within the same linked domain.

If several text segments refer to the same instrument subtype and the same linked domain, merge them into one record and retain the clearest and most representative measure_text as evidence.

Split records only when the text clearly refers to:
1. different instrument subtypes;
2. different policy tools with different governance mechanisms; or
3. different non-food bioeconomy domains.

Do not split a sentence merely because it lists several implementation details under the same policy tool.
Do not count targets, examples, responsible actors, implementation steps, eligible sectors, or beneficiary groups as separate instruments unless they constitute a different instrument subtype.

GATE 5 — Classification:
Assign exactly one primary instrument type and exactly one primary subtype from the allowed coding scheme.
If the record is eligible but the subtype is uncertain or forced, exclude it.
Do not use a financial subtype unless an explicit financial mechanism is stated.
Do not use public procurement unless procurement or government purchasing is explicit.
Do not use licenses unless approval, permit, certificate, registration, authorization, or licensing is explicit.
Do not use production objectives/quotas unless quota, obligation, mandatory target, required share, or indicator is explicit.
Administrative and cooperative instruments must still have a clear non-food bioeconomy object.

GATE 6 — Strict calibration:
For each kept record, code whether the text explicitly specifies the following calibration dimensions for this exact instrument.
Do not infer calibration from the policy title, broad policy context, general objectives, or nearby but unrelated measures.
Do not mark a calibration element as present merely because the instrument exists.
Only mark 1 when the instrument's design or implementation detail is explicitly stated.

- calibration_implementer: 1 only if one or more government actors responsible for implementing this exact instrument are explicitly specified; otherwise 0.
- calibration_funding: 1 only if budget, funding amount, financial resources, subsidy, grant, loan, tax incentive, or another funding arrangement for this exact instrument is explicitly specified; otherwise 0.
- calibration_implementing_partner: 1 only if non-governmental actors involved in implementing this exact instrument are explicitly specified; otherwise 0.
- calibration_timeframe: 1 only if timing, deadline, duration, phase, or implementation period for this exact instrument is explicitly specified; otherwise 0.
- calibration_target_group: 1 only if actors expected to benefit from or change behavior due to this exact instrument are explicitly specified; otherwise 0.
- calibration_procedure: 1 only if concrete procedural steps, task division, eligibility procedures, approval steps, or implementation procedures for this exact instrument are explicitly specified; otherwise 0.
- calibration_content: 1 only if the content, function, design, responsibilities, eligibility criteria, or operational details of this exact instrument are explicitly specified beyond simply naming the instrument; otherwise 0.
- calibration_objective: 1 only if measurable outputs or outcomes for this exact instrument are explicitly specified; otherwise 0.

Allowed classification system:
{classification_json}

Return ONLY valid JSON.
Return only compact records that pass all gates.
If there are no eligible records in this batch, return:
{{"records": []}}

Use this exact JSON structure:
{{
  "records": [
    {{
      "final_decision": "keep",
      "measure_text": "...",
      "evidence_role": "proposed_instrument",
      "jurisdiction_attribution": "focal_jurisdiction",
      "nonfood_bioeconomy_relevance": "direct",
      "linked_domain": "bioenergy | biofuels | biogas | biobased_materials | biochemicals | industrial_biotechnology | biorefinery | biomass_residue_valorization | wood_fiber_materials | forestry_biotechnology | cross_sectoral_bioeconomy",
      "is_concrete_instrument": true,
      "instrument_type": "Economic | Informational | Regulatory | Administrative | Cooperative",
      "instrument_group": "...",
      "instrument_subtype": "...",
      "calibration_implementer": 0,
      "calibration_funding": 0,
      "calibration_implementing_partner": 0,
      "calibration_timeframe": 0,
      "calibration_target_group": 0,
      "calibration_procedure": 0,
      "calibration_content": 0,
      "calibration_objective": 0,
      "justification": "...",
      "confidence": 0.0
    }}
  ]
}}

Policy text context window:
{context}
""".strip()


# =========================================================
# LLM call
# =========================================================
def call_llm(prompt: str) -> Dict[str, Any]:
    last_error = None

    for attempt in range(RETRY_TIMES):
        try:
            resp = oa_client.responses.create(
                model=MODEL_NAME,
                input=prompt,
                temperature=0,
            )
            text = resp.output_text.strip()
            return parse_json_object(text)

        except Exception as e:
            last_error = e
            print(f"[LLM retry {attempt + 1}] {e}")
            time.sleep(2 * (attempt + 1))

    raise RuntimeError(f"LLM call failed after retries: {last_error}")


# =========================================================
# Validation
# =========================================================
def validate_records(
    raw_records: List[Dict[str, Any]],
    batch_id: int,
) -> List[Dict[str, Any]]:
    cleaned = []

    for rec in raw_records:
        decision = clean_str(rec.get("final_decision")).lower()
        if decision != "keep":
            continue

        measure_text = normalize_text(clean_str(rec.get("measure_text")))
        if not measure_text:
            continue

        evidence_role = clean_str(rec.get("evidence_role")).lower()
        jurisdiction_attr = clean_str(rec.get("jurisdiction_attribution")).lower()
        relevance = clean_str(rec.get("nonfood_bioeconomy_relevance")).lower()
        linked_domain = normalize_domain(rec.get("linked_domain"))

        if evidence_role != "proposed_instrument":
            continue
        if jurisdiction_attr != "focal_jurisdiction":
            continue
        if relevance != "direct":
            continue
        if linked_domain not in ALLOWED_DOMAINS:
            continue
        if not normalize_bool(rec.get("is_concrete_instrument")):
            continue

        subtype = clean_str(rec.get("instrument_subtype"))
        if subtype not in ALLOWED_SUBTYPES:
            continue

        confidence = safe_float(rec.get("confidence"), 0.0)
        if confidence < MIN_CONFIDENCE_KEEP:
            continue

        true_type = SUBTYPE_TO_TYPE[subtype]
        true_group = SUBTYPE_TO_GROUP[subtype]
        harmonized_subtype = harmonize_subtype(subtype)

        calibration_values = {}
        for field in CALIBRATION_FIELDS:
            calibration_values[field] = safe_int01(rec.get(field))

        calibration_score = sum(calibration_values.values())

        cleaned.append({
            "batch_id": batch_id,
            "measure_text": measure_text,
            "linked_domain": linked_domain,
            "instrument_type": true_type,
            "instrument_group": true_group,
            "instrument_subtype": subtype,
            "instrument_subtype_harmonized": harmonized_subtype,
            **calibration_values,
            "calibration_score": calibration_score,
            "justification": normalize_text(clean_str(rec.get("justification"))),
            "confidence": round(confidence, 3),
        })

    return cleaned


# =========================================================
# Compact merging: policy × harmonized subtype × linked_domain
# =========================================================
def merge_policy_records(records: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    grouped = {}

    for rec in records:
        harmonized = clean_str(rec.get("instrument_subtype_harmonized"))
        domain = clean_str(rec.get("linked_domain"))
        if not harmonized or not domain:
            continue

        key = (harmonized.lower(), domain.lower())

        if key not in grouped:
            grouped[key] = {
                "records": [],
                "examples": [],
                "batch_ids": set(),
                "raw_subtypes": set(),
            }

        grouped[key]["records"].append(rec)

        text = clean_str(rec.get("measure_text"))
        if text and text not in grouped[key]["examples"]:
            grouped[key]["examples"].append(text)

        batch_id = clean_str(rec.get("batch_id"))
        if batch_id:
            grouped[key]["batch_ids"].add(batch_id)

        raw_subtype = clean_str(rec.get("instrument_subtype"))
        if raw_subtype:
            grouped[key]["raw_subtypes"].add(raw_subtype)

    merged = []

    for item in grouped.values():
        group_records = item["records"]

        def representative_score(r):
            return (
                safe_float(r.get("confidence"), 0.0),
                int(r.get("calibration_score", 0)),
                -len(clean_str(r.get("measure_text"))),
            )

        best = sorted(group_records, key=representative_score, reverse=True)[0]

        representative_calibration = {}
        for field in CALIBRATION_FIELDS:
            representative_calibration[field] = int(best.get(field, 0))

        representative_calibration_score = sum(representative_calibration.values())
        calibrated_yes_no = 1 if representative_calibration_score >= CALIBRATION_THRESHOLD else 0

        avg_confidence = sum(safe_float(r.get("confidence"), 0.0) for r in group_records) / len(group_records)
        max_confidence = max(safe_float(r.get("confidence"), 0.0) for r in group_records)

        evidence_examples = " || ".join(item["examples"][:3])
        evidence_batch_ids = ";".join(
            sorted(item["batch_ids"], key=lambda x: int(x) if x.isdigit() else 999999)
        )
        raw_subtypes_collapsed = " || ".join(sorted(item["raw_subtypes"]))

        merged.append({
            "instrument_type": clean_str(best.get("instrument_type")),
            "instrument_group": clean_str(best.get("instrument_group")),
            "instrument_subtype": clean_str(best.get("instrument_subtype")),
            "instrument_subtype_harmonized": clean_str(best.get("instrument_subtype_harmonized")),
            "raw_subtypes_collapsed": raw_subtypes_collapsed,
            "linked_domain": clean_str(best.get("linked_domain")),
            "evidence_mention_count": len(group_records),
            "evidence_batch_ids": evidence_batch_ids,
            "representative_measure_text": clean_str(best.get("measure_text")),
            "representative_justification": clean_str(best.get("justification")),
            "evidence_examples": evidence_examples,
            **representative_calibration,
            "calibration_score": representative_calibration_score,
            "calibrated_yes_no": calibrated_yes_no,
            "confidence": round(max_confidence, 3),
            "avg_confidence_internal": round(avg_confidence, 3),
        })

    merged.sort(
        key=lambda r: (
            clean_str(r.get("instrument_type")),
            clean_str(r.get("instrument_subtype_harmonized")),
            clean_str(r.get("linked_domain")),
        )
    )

    return merged


# =========================================================
# Summary
# =========================================================
def build_summary_entry(
    row: Dict[str, Any],
    compact_records: List[Dict[str, Any]],
    raw_evidence_mention_count: int,
    original_chunk_count: int,
    seed_chunk_count: int,
    context_chunk_count: int,
    batch_count: int,
) -> Dict[str, Any]:
    policy_id = clean_str(row.get("policy_id"))
    faolex_no = clean_str(row.get("faolex_no"))
    jurisdiction = clean_str(row.get("jurisdiction"))
    policy_year = clean_str(row.get("policy_year"))
    title = clean_str(row.get("title"))
    sector = clean_str(row.get("non_food_bio_based_sector"))

    type_counter = Counter(rec["instrument_type"] for rec in compact_records)
    subtype_raw_set = set(rec["instrument_subtype"] for rec in compact_records)
    subtype_harmonized_set = set(rec["instrument_subtype_harmonized"] for rec in compact_records)
    type_set = set(rec["instrument_type"] for rec in compact_records)

    record_count = len(compact_records)
    calibrated_count = sum(1 for rec in compact_records if int(rec.get("calibrated_yes_no", 0)) == 1)
    calibration_scores = [int(rec.get("calibration_score", 0)) for rec in compact_records]
    confidences = [safe_float(rec.get("confidence"), 0.0) for rec in compact_records]

    return {
        "policy_id": policy_id,
        "faolex_no": faolex_no,
        "jurisdiction": jurisdiction,
        "policy_year": policy_year,
        "title": title,
        "non_food_bio_based_sector": sector,
        "original_chunk_count": original_chunk_count,
        "seed_chunk_count": seed_chunk_count,
        "context_chunk_count": context_chunk_count,
        "batch_count": batch_count,
        "instrument_record_count": record_count,
        "raw_evidence_mention_count": raw_evidence_mention_count,
        "distinct_instrument_types": len(type_set),
        "distinct_instrument_subtypes_raw": len(subtype_raw_set),
        "distinct_instrument_subtypes_harmonized": len(subtype_harmonized_set),
        "Economic": type_counter.get("Economic", 0),
        "Informational": type_counter.get("Informational", 0),
        "Regulatory": type_counter.get("Regulatory", 0),
        "Administrative": type_counter.get("Administrative", 0),
        "Cooperative": type_counter.get("Cooperative", 0),
        "Simpson_balance": simpson_balance(type_counter),
        "calibrated_record_count": calibrated_count,
        "calibrated_record_share": round(calibrated_count / record_count, 4) if record_count else 0.0,
        "avg_calibration_score": round(sum(calibration_scores) / record_count, 4) if record_count else 0.0,
        "avg_confidence": round(sum(confidences) / record_count, 4) if record_count else 0.0,
    }


# =========================================================
# Clean analysis tables
# =========================================================
INSTRUMENT_TYPES = [
    "Economic",
    "Regulatory",
    "Administrative",
    "Cooperative",
    "Informational",
]


def get_dominant_instrument_type(row: Dict[str, Any]) -> Tuple[str, float]:
    total = safe_float(row.get("instrument_record_count"), 0.0)

    if total <= 0:
        return "none", 0.0

    type_counts = {
        instrument_type: safe_float(row.get(instrument_type), 0.0)
        for instrument_type in INSTRUMENT_TYPES
    }

    dominant_type = max(type_counts, key=type_counts.get)
    dominant_count = type_counts[dominant_type]
    dominant_share = dominant_count / total if total else 0.0

    return dominant_type, round(dominant_share, 4)


def classify_policy_mix_profile(row: Dict[str, Any]) -> str:
    total = safe_int(row.get("instrument_record_count"), 0)
    distinct_types = safe_int(row.get("distinct_instrument_types"), 0)
    simpson = safe_float(row.get("Simpson_balance"), 0.0)
    dominant_type, dominant_share = get_dominant_instrument_type(row)

    if total == 0:
        return "no_instrument_detected"

    if distinct_types <= 1:
        return "single_type_policy"

    if dominant_share >= 0.6:
        return f"{dominant_type.lower()}_dominant_policy"

    if distinct_types >= 3 and simpson >= 0.55:
        return "balanced_policy_mix"

    return "mixed_policy"


def build_policy_level_analysis_rows(summary_rows: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    analysis_rows = []

    for row in summary_rows:
        dominant_type, dominant_share = get_dominant_instrument_type(row)

        original_chunks = safe_float(row.get("original_chunk_count"), 0.0)
        context_chunks = safe_float(row.get("context_chunk_count"), 0.0)
        retrieval_coverage = round(context_chunks / original_chunks, 4) if original_chunks else 0.0

        analysis_rows.append({
            "policy_id": clean_str(row.get("policy_id")),
            "faolex_no": clean_str(row.get("faolex_no")),
            "jurisdiction": clean_str(row.get("jurisdiction")),
            "policy_year": clean_str(row.get("policy_year")),
            "title": clean_str(row.get("title")),
            "non_food_bio_based_sector": clean_str(row.get("non_food_bio_based_sector")),
            "instrument_record_count": safe_int(row.get("instrument_record_count")),
            "distinct_instrument_types": safe_int(row.get("distinct_instrument_types")),
            "distinct_instrument_subtypes_harmonized": safe_int(
                row.get("distinct_instrument_subtypes_harmonized")
            ),
            "Economic": safe_int(row.get("Economic")),
            "Regulatory": safe_int(row.get("Regulatory")),
            "Administrative": safe_int(row.get("Administrative")),
            "Cooperative": safe_int(row.get("Cooperative")),
            "Informational": safe_int(row.get("Informational")),
            "dominant_instrument_type": dominant_type,
            "dominant_instrument_share": dominant_share,
            "policy_mix_profile": classify_policy_mix_profile(row),
            "Simpson_balance": safe_float(row.get("Simpson_balance"), 0.0),
            "calibrated_record_share": safe_float(row.get("calibrated_record_share"), 0.0),
            "avg_calibration_score": safe_float(row.get("avg_calibration_score"), 0.0),
            "original_chunk_count": safe_int(row.get("original_chunk_count")),
            "seed_chunk_count": safe_int(row.get("seed_chunk_count")),
            "context_chunk_count": safe_int(row.get("context_chunk_count")),
            "retrieval_coverage": retrieval_coverage,
            "batch_count": safe_int(row.get("batch_count")),
        })

    return analysis_rows


def build_instrument_mix_analysis_rows(record_rows: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    analysis_rows = []

    for row in record_rows:
        analysis_rows.append({
            "policy_id": clean_str(row.get("policy_id")),
            "faolex_no": clean_str(row.get("faolex_no")),
            "jurisdiction": clean_str(row.get("jurisdiction")),
            "policy_year": clean_str(row.get("policy_year")),
            "title": clean_str(row.get("title")),
            "non_food_bio_based_sector": clean_str(row.get("non_food_bio_based_sector")),
            "record_id": clean_str(row.get("record_id")),
            "instrument_type": clean_str(row.get("instrument_type")),
            "instrument_subtype_harmonized": clean_str(row.get("instrument_subtype_harmonized")),
            "linked_domain": clean_str(row.get("linked_domain")),
            "calibration_score": safe_int(row.get("calibration_score")),
            "calibrated_yes_no": safe_int(row.get("calibrated_yes_no")),
            "representative_measure_text": clean_str(row.get("representative_measure_text")),
        })

    return analysis_rows


def save_all_outputs(
    all_records: List[Dict[str, Any]],
    summary_rows: List[Dict[str, Any]],
    log_rows: List[Dict[str, Any]],
) -> None:
    save_csv(OUTPUT_RECORDS, all_records, RECORD_FIELDNAMES)
    save_csv(OUTPUT_SUMMARY, summary_rows, SUMMARY_FIELDNAMES)
    save_csv(OUTPUT_LOG, log_rows, LOG_FIELDNAMES)

    policy_analysis_rows = build_policy_level_analysis_rows(summary_rows)
    mix_analysis_rows = build_instrument_mix_analysis_rows(all_records)

    save_csv(
        OUTPUT_POLICY_ANALYSIS,
        policy_analysis_rows,
        POLICY_LEVEL_ANALYSIS_FIELDNAMES,
    )

    save_csv(
        OUTPUT_MIX_ANALYSIS,
        mix_analysis_rows,
        INSTRUMENT_MIX_ANALYSIS_FIELDNAMES,
    )


# =========================================================
# Main
# =========================================================
def main():
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    catalog = load_csv(INPUT_CATALOG)
    if TEST_LIMIT is not None:
        catalog = catalog[:TEST_LIMIT]

    if RESUME_FROM_EXISTING:
        all_records, summary_rows, log_rows, log_by_policy = load_existing_state()
    else:
        all_records, summary_rows, log_rows, log_by_policy = [], [], [], {}

    retrieval_query_embeddings = None
    if USE_RETRIEVAL_CONTEXT_WINDOWS:
        print(f"Embedding retrieval queries once with model: {EMBEDDING_MODEL}")
        retrieval_query_embeddings = embed_retrieval_queries(RETRIEVAL_QUERIES)
        print(f"Embedded retrieval queries: {len(retrieval_query_embeddings)}")

    print(f"Policies to process: {len(catalog)}")
    if RESUME_FROM_EXISTING:
        done_ok = sum(
            1 for row in log_by_policy.values()
            if clean_str(row.get("status")) == "ok"
        )
        print(f"Resume enabled. Already completed successfully: {done_ok}")

    for idx, row in enumerate(catalog, start=1):
        policy_id = clean_str(row.get("policy_id"))
        faolex_no = clean_str(row.get("faolex_no"))
        jurisdiction = clean_str(row.get("jurisdiction"))
        policy_year = clean_str(row.get("policy_year"))
        title = clean_str(row.get("title"))
        sector = clean_str(row.get("non_food_bio_based_sector"))

        existing_log = log_by_policy.get(policy_id, {})
        if RESUME_FROM_EXISTING and clean_str(existing_log.get("status")) == "ok":
            print(f"\n[{idx}/{len(catalog)}] Skipping completed {policy_id} | {title}")
            continue

        print(f"\n[{idx}/{len(catalog)}] Processing {policy_id} | {title}")

        try:
            chunks = get_policy_chunks(policy_id)
            original_chunk_count = len(chunks)

            if not chunks:
                all_records = remove_policy_rows(all_records, policy_id)
                summary_rows = remove_policy_rows(summary_rows, policy_id)
                log_rows = remove_policy_rows(log_rows, policy_id)

                log_entry = {
                    "policy_id": policy_id,
                    "status": "no_chunks",
                    "message": "No chunks found in vector DB",
                    "original_chunk_count": 0,
                    "seed_chunk_count": 0,
                    "context_chunk_count": 0,
                    "batch_count": 0,
                    "instrument_record_count": 0,
                    "raw_evidence_mention_count": 0,
                }
                log_rows.append(log_entry)
                log_by_policy[policy_id] = log_entry

                save_all_outputs(all_records, summary_rows, log_rows)
                continue

            if USE_RETRIEVAL_CONTEXT_WINDOWS:
                batches, seed_chunk_count, context_chunk_count = retrieve_context_batches_for_policy(
                    policy_id=policy_id,
                    all_chunks=chunks,
                    retrieval_query_embeddings=retrieval_query_embeddings,
                )
                print(
                    f"  - Seed chunks: {seed_chunk_count}; "
                    f"context chunks: {context_chunk_count}/{original_chunk_count}"
                )
            else:
                batches = build_chunk_batches(chunks)
                seed_chunk_count = 0
                context_chunk_count = len(chunks)

            batch_count = len(batches)

            if batch_count == 0:
                all_records = remove_policy_rows(all_records, policy_id)
                summary_rows = remove_policy_rows(summary_rows, policy_id)
                log_rows = remove_policy_rows(log_rows, policy_id)

                log_entry = {
                    "policy_id": policy_id,
                    "status": "empty_context",
                    "message": "No usable text batches built",
                    "original_chunk_count": original_chunk_count,
                    "seed_chunk_count": seed_chunk_count,
                    "context_chunk_count": context_chunk_count,
                    "batch_count": 0,
                    "instrument_record_count": 0,
                    "raw_evidence_mention_count": 0,
                }
                log_rows.append(log_entry)
                log_by_policy[policy_id] = log_entry

                save_all_outputs(all_records, summary_rows, log_rows)
                continue

            policy_raw_records = []

            for batch_i, context in enumerate(batches, start=1):
                print(f"  - Batch {batch_i}/{batch_count}")

                prompt = build_prompt(
                    context=context,
                    policy_id=policy_id,
                    title=title,
                    jurisdiction=jurisdiction,
                    policy_year=policy_year,
                    sector=sector,
                    batch_id=batch_i,
                    batch_count=batch_count,
                )

                raw = call_llm(prompt)
                raw_records = raw.get("records", [])

                if not isinstance(raw_records, list):
                    raise ValueError("Model output field 'records' is not a list")

                cleaned = validate_records(
                    raw_records=raw_records,
                    batch_id=batch_i,
                )
                policy_raw_records.extend(cleaned)

                time.sleep(SLEEP_SECONDS)

            raw_evidence_mention_count = len(policy_raw_records)
            compact_records = merge_policy_records(policy_raw_records)

            all_records = remove_policy_rows(all_records, policy_id)
            summary_rows = remove_policy_rows(summary_rows, policy_id)
            log_rows = remove_policy_rows(log_rows, policy_id)

            policy_output_rows = []
            for rec_i, rec in enumerate(compact_records, start=1):
                policy_output_rows.append({
                    "policy_id": policy_id,
                    "faolex_no": faolex_no,
                    "jurisdiction": jurisdiction,
                    "policy_year": policy_year,
                    "title": title,
                    "non_food_bio_based_sector": sector,
                    "record_id": f"{policy_id}_inst_{rec_i}",
                    **rec,
                })

            all_records.extend(policy_output_rows)

            summary_entry = build_summary_entry(
                row=row,
                compact_records=policy_output_rows,
                raw_evidence_mention_count=raw_evidence_mention_count,
                original_chunk_count=original_chunk_count,
                seed_chunk_count=seed_chunk_count,
                context_chunk_count=context_chunk_count,
                batch_count=batch_count,
            )
            summary_rows.append(summary_entry)

            log_entry = {
                "policy_id": policy_id,
                "status": "ok",
                "message": (
                    f"compact_records={len(policy_output_rows)}; "
                    f"raw_evidence_mentions={raw_evidence_mention_count}"
                ),
                "original_chunk_count": original_chunk_count,
                "seed_chunk_count": seed_chunk_count,
                "context_chunk_count": context_chunk_count,
                "batch_count": batch_count,
                "instrument_record_count": len(policy_output_rows),
                "raw_evidence_mention_count": raw_evidence_mention_count,
            }
            log_rows.append(log_entry)
            log_by_policy[policy_id] = log_entry

            save_all_outputs(all_records, summary_rows, log_rows)

        except Exception as e:
            print(f"[Error] {policy_id}: {e}")

            all_records = remove_policy_rows(all_records, policy_id)
            summary_rows = remove_policy_rows(summary_rows, policy_id)
            log_rows = remove_policy_rows(log_rows, policy_id)

            log_entry = {
                "policy_id": policy_id,
                "status": "error",
                "message": str(e),
                "original_chunk_count": "",
                "seed_chunk_count": "",
                "context_chunk_count": "",
                "batch_count": "",
                "instrument_record_count": "",
                "raw_evidence_mention_count": "",
            }
            log_rows.append(log_entry)
            log_by_policy[policy_id] = log_entry

            save_all_outputs(all_records, summary_rows, log_rows)

    save_all_outputs(all_records, summary_rows, log_rows)

    print("\n=== Done ===")
    print(f"Policy-level analysis table: {OUTPUT_POLICY_ANALYSIS}")
    print(f"Instrument-mix analysis table: {OUTPUT_MIX_ANALYSIS}")
    print(f"Full audit table: {OUTPUT_RECORDS}")
    print(f"Raw summary table: {OUTPUT_SUMMARY}")
    print(f"Log table: {OUTPUT_LOG}")


if __name__ == "__main__":
    main()
